language: elixir
elixir:
  - 1.2.6
  - 1.3.2
otp_release:
  - 18.3
  - 19.0
services: mysql
sudo: false
script:
  - MIX_ENV=mysql mix test
  - MIX_ENV=pg mix test
notifications:
  recipients:
    - elixmoon@gmail.com
